apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: mff
spec:
  restartPolicy: Never
  containers:
    - name: webserver
      startupProbe:
        httpGet:
          path: /
          port: 8080
        periodSeconds: 3
        failureThreshold: 10
      image: osery/webserver:multi
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: 200Mi
          cpu: 200m
        requests:
          memory: 100Mi
          cpu: 100m
